import {useEffect,useState} from 'react'
import {createPortal} from 'react-dom'

async function api(path,options={}){
  const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}})
  const text=await response.text()
  let data={}
  try{data=text?JSON.parse(text):{}}catch{data={detail:text}}
  if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:data.detail?.message||`HTTP ${response.status}`)
  return data
}

const fresh=()=>({company:'',legal_name:'',start_date:new Date().toISOString().slice(0,10),industry:'',market:'',contact_name:'',contact_email:'',contact_phone:'',overview:'',mission:'',objective:'',audience:'',solutions:'',benefits:'',atlaris_scope:'',brand_direction:'Modern, professional, trustworthy'})
const slugify=value=>String(value||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))
const splitItems=value=>String(value||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean)

function makeWebsite(v){
  const solutions=splitItems(v.solutions).map(x=>'<article class="card"><h3>'+escapeHtml(x)+'</h3><p>Designed around customer outcomes and the company objective.</p></article>').join('')
  const benefits=splitItems(v.benefits).map(x=>'<article class="card"><h3>'+escapeHtml(x)+'</h3></article>').join('')
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escapeHtml(v.company)+'</title><style>*{box-sizing:border-box}body{margin:0;font-family:system-ui;background:#07101a;color:#edf4ff;line-height:1.6}.w{width:min(1080px,calc(100% - 40px));margin:auto}header{padding:90px 0;background:radial-gradient(circle at 80% 0,#2859a855,transparent 35%)}h1{font-size:clamp(42px,7vw,76px);line-height:1.04;margin:10px 0}.k{font-size:11px;letter-spacing:.15em;text-transform:uppercase;color:#78a8ff}.lead{max-width:780px;font-size:19px;color:#9badc2}.s{padding:65px 0;border-top:1px solid #17304a}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{padding:22px;border:1px solid #213b56;border-radius:14px;background:#0b1826}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:30px}.meta div{padding:14px;background:#0b1826;border:1px solid #20364e;border-radius:10px}.meta span{display:block;font-size:10px;color:#7189a2;text-transform:uppercase}.meta b{display:block;margin-top:5px}footer{padding:35px 0;color:#71859d;border-top:1px solid #17304a}@media(max-width:800px){.grid,.meta{grid-template-columns:1fr}}</style></head><body><header><div class="w"><div class="k">'+escapeHtml(v.industry||'Company')+'</div><h1>'+escapeHtml(v.objective||v.company)+'</h1><p class="lead">'+escapeHtml(v.overview)+'</p><div class="meta"><div><span>Company</span><b>'+escapeHtml(v.company)+'</b></div><div><span>Started</span><b>'+escapeHtml(v.start_date)+'</b></div><div><span>Market</span><b>'+escapeHtml(v.market||'To be defined')+'</b></div></div></div></header><section class="s"><div class="w"><div class="k">Mission</div><h2>'+escapeHtml(v.mission||v.objective)+'</h2><p class="lead">'+escapeHtml(v.audience)+'</p></div></section><section class="s"><div class="w"><div class="k">Solutions</div><h2>What we deliver</h2><div class="grid">'+solutions+'</div></div></section><section class="s"><div class="w"><div class="k">Benefits</div><h2>Why it matters</h2><div class="grid">'+benefits+'</div></div></section><section class="s"><div class="w"><div class="k">Atlaris delivery</div><h2>Technology scope</h2><p class="lead">'+escapeHtml(v.atlaris_scope)+'</p></div></section><section class="s"><div class="w"><div class="k">Contact</div><h2>'+escapeHtml(v.contact_name||'Contact the team')+'</h2><p>'+escapeHtml(v.contact_email||'Contact details pending')+'</p></div></section><footer><div class="w">Initial customer website generated by Atlaris Technologies.</div></footer></body></html>'
}

function Field({label,children}){return <label><span>{label}</span>{children}</label>}

export default function ClientOnboardingAutomation(){
  const[open,setOpen]=useState(false)
  const[form,setForm]=useState(fresh)
  const[busy,setBusy]=useState(false)
  const[message,setMessage]=useState('')
  const[done,setDone]=useState(null)
  const slug=slugify(form.company)
  const set=(key,value)=>setForm(current=>({...current,[key]:value}))

  useEffect(()=>{
    let lastActive=false
    const timer=setInterval(()=>{
      const active=[...document.querySelectorAll('button.nav-link.active')].some(button=>button.textContent.trim()==='Automation')
      if(active&&!lastActive)setOpen(true)
      if(!active&&lastActive)setOpen(false)
      lastActive=active
    },200)
    return()=>clearInterval(timer)
  },[])

  function close(){
    setOpen(false)
    const overview=[...document.querySelectorAll('button.nav-link')].find(button=>button.textContent.trim()==='Overview')
    overview?.click()
  }

  async function submit(event){
    event.preventDefault()
    if(!slug)return
    setBusy(true)
    setMessage('Creating customer workspace and website on atlas01…')
    try{
      await api('/api/ops/customer/create?customer='+encodeURIComponent(slug),{method:'POST'})
      const profile={...form,slug,created_at:new Date().toISOString()}
      await api('/api/ops/customer/file',{method:'PUT',body:JSON.stringify({customer:slug,path:'onboarding.json',content:JSON.stringify(profile,null,2)})})
      await api('/api/ops/customer/file',{method:'PUT',body:JSON.stringify({customer:slug,path:'index.html',content:makeWebsite(form)})})
      const deployment=await api('/api/ops/customer/deploy-generic?customer='+encodeURIComponent(slug),{method:'POST'})
      setDone({slug,deployment})
      setMessage('Client and local website created successfully.')
    }catch(error){setMessage(error.message)}finally{setBusy(false)}
  }

  if(!open)return null
  return createPortal(<div className="coa"><header><div><small>ATLARIS AUTOMATION</small><h2>New Client Onboarding</h2><p>Create the client profile and initial managed website on atlas01.</p></div><button onClick={close}>Close</button></header>{message&&<div className={done?'note good':'note'}>{message}</div>}{done?<section className="card success"><h3>Client created</h3><p>{form.company} now has an onboarding profile, website source and managed local deployment.</p><code>/opt/atlaris-customers/websites/{done.slug}/</code><code>/opt/atlaris-customers/backups/{done.slug}/</code><code>/var/www/atlaris-customers/{done.slug}/</code><button onClick={()=>{setForm(fresh());setDone(null);setMessage('')}}>Create another client</button></section>:<form onSubmit={submit}><section className="card"><h3>Company information</h3><div className="grid"><Field label="Company name"><input value={form.company} onChange={e=>set('company',e.target.value)} required/></Field><Field label="Legal business name"><input value={form.legal_name} onChange={e=>set('legal_name',e.target.value)}/></Field><Field label="Start / onboarding date"><input type="date" value={form.start_date} onChange={e=>set('start_date',e.target.value)} required/></Field><Field label="Industry"><input value={form.industry} onChange={e=>set('industry',e.target.value)} required/></Field><Field label="Primary market"><input value={form.market} onChange={e=>set('market',e.target.value)}/></Field><Field label="Generated customer slug"><input value={slug} readOnly/></Field></div></section><section className="card"><h3>Primary contact</h3><div className="grid"><Field label="Contact name"><input value={form.contact_name} onChange={e=>set('contact_name',e.target.value)} required/></Field><Field label="Email"><input type="email" value={form.contact_email} onChange={e=>set('contact_email',e.target.value)} required/></Field><Field label="Phone"><input value={form.contact_phone} onChange={e=>set('contact_phone',e.target.value)}/></Field></div></section><section className="card"><h3>Business and website requirements</h3><div className="one"><Field label="Company overview"><textarea rows="4" value={form.overview} onChange={e=>set('overview',e.target.value)} required/></Field><Field label="Mission"><textarea rows="3" value={form.mission} onChange={e=>set('mission',e.target.value)} required/></Field><Field label="Primary company objective"><textarea rows="3" value={form.objective} onChange={e=>set('objective',e.target.value)} required/></Field><Field label="Target audience"><textarea rows="3" value={form.audience} onChange={e=>set('audience',e.target.value)} required/></Field><Field label="Solutions to deliver"><textarea rows="4" value={form.solutions} onChange={e=>set('solutions',e.target.value)} required/></Field><Field label="Benefits / value proposition"><textarea rows="4" value={form.benefits} onChange={e=>set('benefits',e.target.value)} required/></Field><Field label="Atlaris delivery scope"><textarea rows="4" value={form.atlaris_scope} onChange={e=>set('atlaris_scope',e.target.value)} placeholder="Website, hosting, monitoring, automation, AI, support…" required/></Field><Field label="Brand / website direction"><textarea rows="3" value={form.brand_direction} onChange={e=>set('brand_direction',e.target.value)}/></Field></div></section><section className="card paths"><h3>Automatic local creation</h3><p>Submitting creates the controlled customer source, backup area and deployment root.</p><code>/opt/atlaris-customers/websites/{slug||'client-slug'}/</code><code>/opt/atlaris-customers/backups/{slug||'client-slug'}/</code><code>/var/www/atlaris-customers/{slug||'client-slug'}/</code><button className="primary" disabled={busy}>{busy?'Creating on atlas01…':'Create client + website'}</button></section></form>}<style>{`.coa{position:fixed;z-index:600;inset:0 0 0 194px;overflow:auto;padding:32px 40px 70px;background:radial-gradient(circle at 82% 0,#204d8e33,transparent 30%),#07101a;color:#edf4ff}.coa>header{max-width:1160px;margin:auto;display:flex;justify-content:space-between;gap:20px}.coa h2{font-size:34px;margin:5px 0}.coa header p{color:#8298b1}.coa small{color:#6f94c6;letter-spacing:.14em}.coa button{background:#0c1928;color:#dae5f2;border:1px solid #2a445f;border-radius:9px;padding:10px 13px;cursor:pointer}.coa form,.coa .card,.coa .note{max-width:1160px;margin:15px auto}.coa .card{border:1px solid #20364d;border-radius:14px;background:#0b1725;padding:22px}.coa .card h3{margin-top:0}.coa .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.coa .one{display:grid;gap:12px}.coa label{display:grid;gap:6px;color:#9db0c5;font-size:11px;font-weight:700}.coa label>span{font-size:11px}.coa input,.coa textarea{width:100%;background:#07131f;border:1px solid #29415a;border-radius:8px;padding:10px;color:#fff}.coa input[readonly]{color:#77a7e9}.coa .paths code,.coa .success code{display:block;background:#07131f;padding:10px;border-radius:8px;margin:7px 0;color:#96b7dc;overflow-wrap:anywhere}.coa .primary{margin-top:14px;background:linear-gradient(135deg,#3159d8,#2547b4);border-color:#557df0}.coa .note{padding:13px;border:1px solid #6b5227;background:#2d2312;color:#e0be72;border-radius:9px}.coa .note.good{border-color:#2b5b4a;background:#102b23;color:#7bd3b4}.coa .success{text-align:center}.coa .success button{margin-top:15px}@media(max-width:900px){.coa{inset:0;padding:20px}.coa .grid{grid-template-columns:1fr}.coa>header{flex-direction:column}}`}</style></div>,document.body)
}
