import {useEffect,useState} from 'react'
import{createPortal}from'react-dom'

const FIN='/api/finance'
async function getJson(path){const r=await fetch(path,{credentials:'same-origin',cache:'no-store'});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={detail:t}}if(!r.ok)throw Error(d.detail||`HTTP ${r.status}`);return d}
const fmt=v=>v?new Date(v).toLocaleString():'—'
function Pill({ok,label}){return <span className={`rd-pill ${ok?'ok':'warn'}`}>{label}</span>}

function Panel({close}){
 const[data,setData]=useState(null),[err,setErr]=useState('')
 async function load(){try{const[health,access,backups,automation,settings,reports,runs,notifications]=await Promise.all([getJson(`${FIN}/health`),getJson(`${FIN}/access-context`),getJson(`${FIN}/backup-status`),getJson(`${FIN}/automations`),getJson(`${FIN}/settings`),getJson(`${FIN}/report-schedules`),getJson(`${FIN}/automation-runs?limit=20`),getJson(`${FIN}/notifications?limit=50`)]);const settingMap=Object.fromEntries((settings||[]).map(x=>[x.setting_key,x.setting_value]));setData({health,access,backups,automation,settingMap,reports,runs,notifications});setErr('')}catch(e){setErr(e.message)}}
 useEffect(()=>{load()},[])
 if(!data)return <div className="rd-shell"><header><div><span>ATLARIS ADMINISTRATION</span><h2>System Readiness</h2><p>Production integration and Finance control status.</p></div><button onClick={close}>Close</button></header>{err?<div className="rd-error">{err}</div>:<div className="rd-loading">Loading operational status…</div>}</div>
 const pay=data.settingMap.payments||{},enabled=data.automation.filter(x=>x.enabled).length,failed=data.automation.filter(x=>x.last_status&&x.last_status!=='success').length,queued=data.notifications.filter(x=>x.status==='queued').length,needsRecipient=data.notifications.filter(x=>x.status==='needs_recipient').length,schedulerReady=data.automation.some(x=>x.next_run_at)
 const checks=[
  {name:'Finance API',ok:data.health.status==='healthy',detail:data.health.status||'Unknown'},
  {name:'Finance RBAC',ok:Boolean(data.access.role),detail:`${data.access.role||'Unassigned'} · ${data.access.principal||'No principal'}`},
  {name:'Database backups',ok:Boolean(data.backups.latest),detail:data.backups.latest?`Latest ${fmt(data.backups.latest.modified_at)}`:'No backup found'},
  {name:'Automation scheduler',ok:schedulerReady&&failed===0,detail:`${enabled}/${data.automation.length} enabled · next-run scheduling active${failed?` · ${failed} need review`:''}`},
  {name:'Automation history',ok:true,detail:`${data.runs.length} recent run record(s) visible`},
  {name:'Notification queue',ok:true,detail:`${queued} queued · ${needsRecipient} need recipient`},
  {name:'PDF / XLSX exports',ok:true,detail:'Executive PDF and collections XLSX endpoints active'},
  {name:'Report schedules',ok:true,detail:`${data.reports.length} configured`},
  {name:'Online payments',ok:Boolean(pay.online_payments_enabled),detail:pay.online_payments_enabled?`${pay.processor||'Configured'} enabled`:`Manual mode · ${pay.processor||'no provider'} processor`},
  {name:'Outbound email/SMS',ok:false,detail:'Queue ready; approved transport not connected'},
  {name:'Multi-user identity',ok:data.access.principal!=='dashboard-admin',detail:data.access.principal==='dashboard-admin'?'Single dashboard-admin identity':'Per-user identity active'},
  {name:'Database restore helper',ok:false,detail:'Privileged restore helper not exposed to Dashboard'},
 ]
 return <div className="rd-shell"><header><div><span>ATLARIS ADMINISTRATION</span><h2>System Readiness</h2><p>Live production status for Finance, payments, automation, reporting and recovery controls.</p></div><div className="rd-actions"><button onClick={load}>Refresh</button><button onClick={close}>Close</button></div></header>
  {err&&<div className="rd-error">{err}</div>}
  <section className="rd-summary"><article><span>Finance service</span><strong>{data.health.status}</strong></article><article><span>Finance role</span><strong>{data.access.role}</strong></article><article><span>Backups visible</span><strong>{data.backups.count}</strong></article><article><span>Automations enabled</span><strong>{enabled}</strong></article></section>
  <section className="rd-grid">{checks.map(x=><article key={x.name}><div><span>{x.name}</span><Pill ok={x.ok} label={x.ok?'Ready':'Action needed'}/></div><p>{x.detail}</p></article>)}</section>
  <section className="rd-panel"><h3>What is fully operational now</h3><p>Finance API, RBAC, customer payment recording, credits/refunds, customer collection notes, scheduled automation execution, run history, notification queueing, PDF/XLSX exports, settings, reporting schedules, document handling, approvals and controlled backups are connected to the production Dashboard.</p></section>
  <section className="rd-panel"><h3>External integrations still required</h3><div className="rd-list"><div><b>Payment processor</b><span>Connect an approved provider account before enabling live card or bank checkout.</span></div><div><b>Email / SMS transport</b><span>The queue is ready; SMTP, OAuth mail, or a messaging provider is required for actual delivery.</span></div><div><b>Per-user authentication</b><span>The authentication service must expose a trusted user identity instead of the current shared administrator principal.</span></div><div><b>Restore helper</b><span>A privileged, audited PostgreSQL restore operation must be exposed by the server control plane before web restore can be enabled.</span></div></div></section>
  <section className="rd-panel"><h3>Recent automation state</h3><div className="rd-mini-table">{data.automation.map(x=><div key={x.rule_type}><span>{x.rule_type.replaceAll('_',' ')}</span><b>{x.enabled?'Enabled':'Disabled'}</b><em>{x.last_status||'Not run'}</em><small>{x.next_run_at?`Next ${fmt(x.next_run_at)}`:`Last ${fmt(x.last_run_at)}`}</small></div>)}</div></section>
 </div>
}

export default function ReadinessModule(){
 const[host,setHost]=useState(null),[open,setOpen]=useState(false)
 useEffect(()=>{let stop=false,t;const sync=()=>{if(stop)return;const groups=[...document.querySelectorAll('.nav-group')],admin=groups.find(x=>x.querySelector('.sidebar-section-label')?.textContent.trim()==='Administration');setHost(admin?.querySelector('.nav-list')||null);t=setTimeout(sync,500)};sync();return()=>{stop=true;clearTimeout(t)}},[])
 function show(){const nav=host;if(nav)for(const b of nav.querySelectorAll('button.nav-link'))b.classList.remove('active');setOpen(true)}
 function close(){setOpen(false)}
 return <>{host&&createPortal(<button className={`nav-link${open?' active':''}`} onClick={show}><span>◉</span>System Health</button>,host)}{open&&createPortal(<Panel close={close}/>,document.body)}<style>{`.rd-shell{position:fixed;z-index:250;inset:0 0 0 264px;overflow:auto;padding:32px;color:#e9f1fb;background:radial-gradient(circle at 90% 0,rgba(78,112,230,.16),transparent 30%),linear-gradient(155deg,#07101b,#091521 50%,#071019)}.rd-shell>header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.rd-shell>header span{font-size:9px;letter-spacing:.14em;color:#718bb0;font-weight:900}.rd-shell h2{font-size:32px;margin:6px 0}.rd-shell p{color:#8398b0}.rd-shell button{border:1px solid #29415b;background:#0b1827;color:#c7d4e4;border-radius:9px;padding:9px 11px;cursor:pointer}.rd-actions{display:flex;gap:8px}.rd-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.rd-summary article,.rd-grid article,.rd-panel{border:1px solid #20364e;background:linear-gradient(145deg,#0d1a2a,#09131f);border-radius:14px;padding:17px}.rd-summary span{display:block;font-size:9px;text-transform:uppercase;color:#7188a1}.rd-summary strong{display:block;margin-top:8px;font-size:21px;text-transform:capitalize}.rd-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.rd-grid article>div{display:flex;justify-content:space-between;align-items:center;gap:8px}.rd-grid article>div>span{font-size:12px;font-weight:800}.rd-grid p{margin:13px 0 0;font-size:11px;line-height:1.5}.rd-pill{white-space:nowrap;padding:6px 8px;border-radius:999px;font-size:9px;font-weight:800}.rd-pill.ok{background:#0d2722;border:1px solid #285948;color:#79d5b5}.rd-pill.warn{background:#2b2111;border:1px solid #665026;color:#e0bc72}.rd-panel{margin-top:14px}.rd-panel h3{margin:0 0 8px}.rd-list{display:grid;gap:8px}.rd-list div{display:grid;grid-template-columns:180px 1fr;gap:12px;padding:10px;border-radius:9px;background:#081420;border:1px solid #1b3047}.rd-list b{font-size:11px}.rd-list span{font-size:11px;color:#8096af}.rd-mini-table{display:grid}.rd-mini-table>div{display:grid;grid-template-columns:2fr .7fr .8fr 1.4fr;gap:10px;padding:9px 0;border-bottom:1px solid #182b3f;align-items:center}.rd-mini-table span{font-size:11px;text-transform:capitalize}.rd-mini-table b,.rd-mini-table em,.rd-mini-table small{font-size:10px;color:#8299b2;font-style:normal}.rd-error,.rd-loading{margin-top:20px;padding:14px;border-radius:10px;border:1px solid #6d313e;background:#2c151c;color:#f09da8}.rd-loading{border-color:#29415b;background:#0b1827;color:#9ab0c7}@media(max-width:1000px){.rd-summary{grid-template-columns:1fr 1fr}.rd-grid{grid-template-columns:1fr 1fr}}@media(max-width:900px){.rd-shell{inset:0;padding:18px}.rd-summary,.rd-grid{grid-template-columns:1fr}.rd-list div,.rd-mini-table>div{grid-template-columns:1fr}}`}</style></>}
